import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MySidebar from "@/components/sidebar";
import { Providers } from "@/components/toast/toast-provider";
const interFont = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
				<html lang="en">
					<body
							className={`antialiased`}
					>
						<MySidebar />
						<Header />
						{children}
						 <Providers />
						<Footer	/>
					</body>
				</html>
  );
}
